-- Generado por scripts/generate-i18n-seed.js — no editar a mano
-- Namespaces: HEADER, FOOTER, SUGGESTIONS, SOURCES, FEEDBACK, SIDEBAR, WELCOME, HOME, LEGAL

insert into public.i18n_translations (namespace, key, locale, value)
values
  ('HEADER', 'LOGOUT', 'en', 'LOG OUT'),
  ('FOOTER', 'TERMS', 'en', 'Terms'),
  ('FOOTER', 'PRIVACY', 'en', 'Privacy'),
  ('FOOTER', 'COOKIES', 'en', 'Cookies Policy'),
  ('FOOTER', 'LEGAL_NOTICE', 'en', 'Legal Notice'),
  ('FOOTER', 'GRANT_NUMBER', 'en', 'CGI-Clinics GA No.101057509.'),
  ('FOOTER', 'CGI_CLINICS', 'en', 'CGI-Clinics'),
  ('FOOTER', 'CANCER_GENOME_INTERPRETER', 'en', 'Cancer Genome Interpreter'),
  ('FOOTER', 'COPYRIGHT', 'en', '© 2025 | Cancer Genome Interpreter Clinics | All Rights Reserved'),
  ('FOOTER', 'GRANT_INFO_TITLE', 'en', 'Grant Information'),
  ('FOOTER', 'GRANT_INFO_TEXT', 'en', 'Funded by the European Union. Views and opinions expressed are however those of the author(s) only and do not necessarily reflect those of the European Union or the European Health and Digital Executive Agency (HADEA). Neither the European Union nor the granting authority can be held responsible for them.'),
  ('FOOTER', 'TERMS_TEXT', 'en', 'By messaging eduCGI, you agree to our'),
  ('FOOTER', 'AND_READ', 'en', 'and have read our'),
  ('FOOTER', 'AND', 'en', 'and'),
  ('SUGGESTIONS', 'CANCER_MUTATIONS', 'en', 'Tell me more about cancer mutations'),
  ('SUGGESTIONS', 'TREATMENT_OPTIONS', 'en', 'What are the treatment options?'),
  ('SUGGESTIONS', 'GENOMIC_SEQUENCING', 'en', 'Explain genomic sequencing'),
  ('SUGGESTIONS', 'IMMUNOTHERAPY_WORK', 'en', 'How does immunotherapy work?'),
  ('SUGGESTIONS', 'WHAT_IS_CANCER', 'en', 'What is cancer?'),
  ('SUGGESTIONS', 'CANCER_MUTATION', 'en', 'What is a cancer mutation?'),
  ('SUGGESTIONS', 'GENOMIC_SEQUENCING_DIAGNOSIS', 'en', 'How does genomic sequencing help in cancer diagnosis?'),
  ('SUGGESTIONS', 'SOMATIC_GERMLINE_DIFFERENCE', 'en', 'Explain the difference between somatic and germline mutations.'),
  ('SOURCES', 'TITLE', 'en', 'Source'),
  ('SOURCES', 'REFERENCES', 'en', 'References'),
  ('FEEDBACK', 'ADDITIONAL_FEEDBACK', 'en', 'Additional feedback'),
  ('FEEDBACK', 'TELL_US_MORE', 'en', 'Tell us more about your experience...'),
  ('FEEDBACK', 'CANCEL', 'en', 'Cancel'),
  ('FEEDBACK', 'SUBMIT', 'en', 'Submit'),
  ('FEEDBACK', 'SENDING', 'en', 'Sending feedback'),
  ('FEEDBACK', 'LIKE_SENT', 'en', 'Liked'),
  ('FEEDBACK', 'LIKE_ACTION', 'en', 'Like this response'),
  ('FEEDBACK', 'DISLIKE_SENT', 'en', 'Disliked'),
  ('FEEDBACK', 'DISLIKE_ACTION', 'en', 'Dislike this response'),
  ('FEEDBACK', 'REGENERATE_RESPONSE', 'en', 'Regenerate response'),
  ('FEEDBACK', 'STOP', 'en', 'Stop'),
  ('SIDEBAR', 'NEW_CHAT', 'en', 'New chat'),
  ('SIDEBAR', 'CHAT_HISTORY', 'en', 'Chat history'),
  ('SIDEBAR', 'SEARCH_PLACEHOLDER', 'en', 'Search...'),
  ('SIDEBAR', 'CLEAR_HISTORY', 'en', 'Clear history'),
  ('SIDEBAR', 'HEALTH_PROFILE', 'en', 'My health profile'),
  ('SIDEBAR', 'HEALTH_PROFILE_TOOLTIP', 'en', 'View your health profile'),
  ('SIDEBAR', 'KNOW_MORE', 'en', 'Know more'),
  ('SIDEBAR', 'ABOUT_US', 'en', 'About us'),
  ('SIDEBAR', 'FAQS', 'en', 'FAQs'),
  ('SIDEBAR', 'SOURCES', 'en', 'Sources'),
  ('SIDEBAR', 'NO_RECENT_CONVERSATIONS', 'en', 'No recent conversations'),
  ('SIDEBAR', 'NO_MATCHING_QUESTIONS', 'en', 'No questions found matching'),
  ('SIDEBAR', 'YOUR_CONVERSATIONS', 'en', 'Your conversations...'),
  ('SIDEBAR', 'ALL_QUESTIONS_ANSWERED', 'en', 'All suggested questions have been answered'),
  ('SIDEBAR', 'DELETE_CONVERSATION_CONFIRM', 'en', 'Are you sure you want to delete this conversation?'),
  ('SIDEBAR', 'HEALTH_PROFILE_INFO', 'en', 'This context information will be used as a filter into eduCGI'),
  ('SIDEBAR', 'HEALTH_PROFILE_TOGGLE_TOOLTIP', 'en', 'Toggle inclusion of health profile in chat'),
  ('SIDEBAR', 'HEALTH_PARAM_TUMOR_TYPE', 'en', 'Tumor type'),
  ('SIDEBAR', 'HEALTH_PARAM_TUMOR_ALTERATION', 'en', 'Tumor alteration'),
  ('SIDEBAR', 'HEALTH_PARAM_TREATMENT', 'en', 'Treatment'),
  ('WELCOME', 'HELLO', 'en', 'Hello'),
  ('WELCOME', 'HELP_TODAY', 'en', 'How may I help you today?'),
  ('WELCOME', 'SUGGESTED_QUESTIONS', 'en', 'Suggested questions'),
  ('HOME', 'WELCOME_TITLE', 'en', 'Welcome to eduCGI!'),
  ('HOME', 'DESCRIPTION_1', 'en', 'As an <strong>AI chatbot</strong>, I''m here to help you understand the complex world of cancer on a molecular level. My goal is to make scientific information more accessible, providing clear explanations based on reliable sources.'),
  ('HOME', 'DESCRIPTION_2', 'en', '<strong>Please remember: I am an AI, not a medical professional.</strong> The information I share is for educational purposes only and should never be used for self-diagnosis or to make medical decisions. Always consult with a qualified healthcare provider for personalized medical advice and treatment.'),
  ('HOME', 'AGREEMENT_TEXT', 'en', 'eduCGI is developed within the CGI-Clinics project'),
  ('HOME', 'AGREEMENT_LINK', 'en', 'agreement CGI-Clinics 101057509'),
  ('HOME', 'START_BUTTON', 'en', 'START'),
  ('HOME', 'AGREEMENT_TITLE', 'en', 'Agreement CGI-Clinics 101057509'),
  ('HOME', 'AGREEMENT_CONTENT', 'en', 'Funded by the European Union. Views and opinions expressed are however those of the author(s) only and do not necessarily reflect those of the European Union or the European Health and Digital Executive Agency (HADEA). Neither the European Union nor the granting authority can be held responsible for them.'),
  ('HOME', 'CLOSE_BUTTON', 'en', 'Close'),
  ('LEGAL', 'TERMS_TITLE', 'en', 'Terms and Conditions'),
  ('LEGAL', 'PRIVACY_TITLE', 'en', 'Privacy Policy'),
  ('LEGAL', 'COOKIES_TITLE', 'en', 'Cookies Policy'),
  ('LEGAL', 'LEGAL_NOTICE_TITLE', 'en', 'Legal Notice'),
  ('LEGAL', 'DEFAULT_TITLE', 'en', 'Legal Information'),
  ('LEGAL', 'UNDER_REVISION', 'en', 'Text under revision'),
  ('LEGAL', 'PLACEHOLDER_TEXT', 'en', 'This content is currently being reviewed and will be available soon.'),
  ('LEGAL', 'BACK_HOME', 'en', 'Back to Home'),
  ('HEADER', 'LOGOUT', 'es', 'CERRAR SESIÓN'),
  ('FOOTER', 'TERMS', 'es', 'Términos'),
  ('FOOTER', 'PRIVACY', 'es', 'Privacidad'),
  ('FOOTER', 'COOKIES', 'es', 'Política de Cookies'),
  ('FOOTER', 'LEGAL_NOTICE', 'es', 'Aviso Legal'),
  ('FOOTER', 'GRANT_NUMBER', 'es', 'CGI-Clinics GA No.101057509.'),
  ('FOOTER', 'CGI_CLINICS', 'es', 'CGI-Clinics'),
  ('FOOTER', 'CANCER_GENOME_INTERPRETER', 'es', 'Cancer Genome Interpreter'),
  ('FOOTER', 'COPYRIGHT', 'es', '© 2025 | Cancer Genome Interpreter Clinics | Todos los derechos reservados'),
  ('FOOTER', 'GRANT_INFO_TITLE', 'es', 'Información de la Subvención'),
  ('FOOTER', 'GRANT_INFO_TEXT', 'es', 'Financiado por la Unión Europea. Las opiniones y puntos de vista expresados son, sin embargo, los del autor o autores solamente y no reflejan necesariamente los de la Unión Europea o la Agencia Ejecutiva de Salud y Digital (HADEA). Ni la Unión Europea ni la autoridad concedente pueden ser consideradas responsables de ellos.'),
  ('FOOTER', 'TERMS_TEXT', 'es', 'Al enviar mensajes a eduCGI, aceptas nuestros'),
  ('FOOTER', 'AND_READ', 'es', 'y has leído nuestra'),
  ('FOOTER', 'AND', 'es', 'y'),
  ('SUGGESTIONS', 'CANCER_MUTATIONS', 'es', 'Cuéntame más sobre las mutaciones del cáncer'),
  ('SUGGESTIONS', 'TREATMENT_OPTIONS', 'es', '¿Qué opciones de tratamiento existen?'),
  ('SUGGESTIONS', 'GENOMIC_SEQUENCING', 'es', 'Explica la secuenciación genómica'),
  ('SUGGESTIONS', 'IMMUNOTHERAPY_WORK', 'es', '¿Cómo funciona la inmunoterapia?'),
  ('SUGGESTIONS', 'WHAT_IS_CANCER', 'es', '¿Qué es el cáncer?'),
  ('SUGGESTIONS', 'CANCER_MUTATION', 'es', '¿Qué es una mutación del cáncer?'),
  ('SUGGESTIONS', 'GENOMIC_SEQUENCING_DIAGNOSIS', 'es', '¿Cómo ayuda la secuenciación genómica en el diagnóstico del cáncer?'),
  ('SUGGESTIONS', 'SOMATIC_GERMLINE_DIFFERENCE', 'es', 'Explica la diferencia entre mutaciones somáticas y germinales.'),
  ('SOURCES', 'TITLE', 'es', 'Fuente'),
  ('SOURCES', 'REFERENCES', 'es', 'Referencias'),
  ('FEEDBACK', 'ADDITIONAL_FEEDBACK', 'es', 'Comentarios adicionales'),
  ('FEEDBACK', 'TELL_US_MORE', 'es', 'Cuéntanos más sobre tu experiencia...'),
  ('FEEDBACK', 'CANCEL', 'es', 'Cancelar'),
  ('FEEDBACK', 'SUBMIT', 'es', 'Enviar'),
  ('FEEDBACK', 'SENDING', 'es', 'Enviando comentarios'),
  ('FEEDBACK', 'LIKE_SENT', 'es', 'Me gusta enviado'),
  ('FEEDBACK', 'LIKE_ACTION', 'es', 'Me gusta esta respuesta'),
  ('FEEDBACK', 'DISLIKE_SENT', 'es', 'No me gusta enviado'),
  ('FEEDBACK', 'DISLIKE_ACTION', 'es', 'No me gusta esta respuesta'),
  ('FEEDBACK', 'REGENERATE_RESPONSE', 'es', 'Regenerar respuesta'),
  ('FEEDBACK', 'STOP', 'es', 'Detener'),
  ('SIDEBAR', 'NEW_CHAT', 'es', 'Nuevo chat'),
  ('SIDEBAR', 'CHAT_HISTORY', 'es', 'Historial de chat'),
  ('SIDEBAR', 'SEARCH_PLACEHOLDER', 'es', 'Buscar...'),
  ('SIDEBAR', 'CLEAR_HISTORY', 'es', 'Limpiar historial'),
  ('SIDEBAR', 'HEALTH_PROFILE', 'es', 'Mi perfil de salud'),
  ('SIDEBAR', 'HEALTH_PROFILE_TOOLTIP', 'es', 'Ver tu perfil de salud'),
  ('SIDEBAR', 'KNOW_MORE', 'es', 'Saber más'),
  ('SIDEBAR', 'ABOUT_US', 'es', 'Sobre nosotros'),
  ('SIDEBAR', 'FAQS', 'es', 'Preguntas frecuentes'),
  ('SIDEBAR', 'SOURCES', 'es', 'Fuentes'),
  ('SIDEBAR', 'NO_RECENT_CONVERSATIONS', 'es', 'No hay conversaciones recientes'),
  ('SIDEBAR', 'NO_MATCHING_QUESTIONS', 'es', 'No se encontraron preguntas que coincidan con'),
  ('SIDEBAR', 'YOUR_CONVERSATIONS', 'es', 'Tus conversaciones...'),
  ('SIDEBAR', 'ALL_QUESTIONS_ANSWERED', 'es', 'Todas las preguntas sugeridas han sido respondidas'),
  ('SIDEBAR', 'DELETE_CONVERSATION_CONFIRM', 'es', '¿Seguro que quieres eliminar esta conversación?'),
  ('SIDEBAR', 'HEALTH_PROFILE_INFO', 'es', 'Esta información de contexto se usará como filtro en eduCGI'),
  ('SIDEBAR', 'HEALTH_PROFILE_TOGGLE_TOOLTIP', 'es', 'Incluir o excluir el perfil de salud en el chat'),
  ('SIDEBAR', 'HEALTH_PARAM_TUMOR_TYPE', 'es', 'Tipo de tumor'),
  ('SIDEBAR', 'HEALTH_PARAM_TUMOR_ALTERATION', 'es', 'Alteración del tumor'),
  ('SIDEBAR', 'HEALTH_PARAM_TREATMENT', 'es', 'Tratamiento'),
  ('WELCOME', 'HELLO', 'es', 'Hola'),
  ('WELCOME', 'HELP_TODAY', 'es', '¿Cómo puedo ayudarte hoy?'),
  ('WELCOME', 'SUGGESTED_QUESTIONS', 'es', 'Preguntas sugeridas'),
  ('HOME', 'WELCOME_TITLE', 'es', '¡Bienvenido a eduCGI!'),
  ('HOME', 'DESCRIPTION_1', 'es', 'Como un <strong>chatbot de IA</strong>, estoy aquí para ayudarte a comprender el complejo mundo del cáncer a nivel molecular. Mi objetivo es hacer que la información científica sea más accesible, proporcionando explicaciones claras basadas en fuentes confiables.'),
  ('HOME', 'DESCRIPTION_2', 'es', '<strong>Por favor recuerda: Soy una IA, no un profesional médico.</strong> La información que comparto es solo con fines educativos y nunca debe usarse para autodiagnóstico o para tomar decisiones médicas. Siempre consulte con un proveedor de atención médica calificado para obtener asesoramiento y tratamiento personalizado.'),
  ('HOME', 'AGREEMENT_TEXT', 'es', 'eduCGI se desarrolla dentro del proyecto CGI-Clinics'),
  ('HOME', 'AGREEMENT_LINK', 'es', 'acuerdo CGI-Clinics 101057509'),
  ('HOME', 'START_BUTTON', 'es', 'COMENZAR'),
  ('HOME', 'AGREEMENT_TITLE', 'es', 'Acuerdo CGI-Clinics 101057509'),
  ('HOME', 'AGREEMENT_CONTENT', 'es', 'Financiado por la Unión Europea. Las opiniones y puntos de vista expresados son, sin embargo, los del autor o autores solamente y no reflejan necesariamente los de la Unión Europea o la Agencia Ejecutiva de Salud y Digital (HADEA). Ni la Unión Europea ni la autoridad concedente pueden ser consideradas responsables de ellos.'),
  ('HOME', 'CLOSE_BUTTON', 'es', 'Cerrar'),
  ('LEGAL', 'TERMS_TITLE', 'es', 'Términos y Condiciones'),
  ('LEGAL', 'PRIVACY_TITLE', 'es', 'Política de Privacidad'),
  ('LEGAL', 'COOKIES_TITLE', 'es', 'Política de Cookies'),
  ('LEGAL', 'LEGAL_NOTICE_TITLE', 'es', 'Aviso Legal'),
  ('LEGAL', 'DEFAULT_TITLE', 'es', 'Información Legal'),
  ('LEGAL', 'UNDER_REVISION', 'es', 'Texto en revisión'),
  ('LEGAL', 'PLACEHOLDER_TEXT', 'es', 'Este contenido está siendo revisado y estará disponible próximamente.'),
  ('LEGAL', 'BACK_HOME', 'es', 'Volver al inicio'),
  ('HEADER', 'LOGOUT', 'fr', 'SE DÉCONNECTER'),
  ('FOOTER', 'TERMS', 'fr', 'Conditions'),
  ('FOOTER', 'PRIVACY', 'fr', 'Confidentialité'),
  ('FOOTER', 'COOKIES', 'fr', 'Politique des cookies'),
  ('FOOTER', 'LEGAL_NOTICE', 'fr', 'Avis légal'),
  ('FOOTER', 'GRANT_NUMBER', 'fr', 'CGI-Clinics GA No.101057509.'),
  ('FOOTER', 'CGI_CLINICS', 'fr', 'CGI-Clinics'),
  ('FOOTER', 'CANCER_GENOME_INTERPRETER', 'fr', 'Cancer Genome Interpreter'),
  ('FOOTER', 'COPYRIGHT', 'fr', '© 2025 | Cancer Genome Interpreter Clinics | Tous droits réservés'),
  ('FOOTER', 'GRANT_INFO_TITLE', 'fr', 'Informations sur le financement'),
  ('FOOTER', 'GRANT_INFO_TEXT', 'fr', 'Financé par l''Union européenne. Les opinions exprimées n''engagent que leur(s) auteur(s) et ne reflètent pas nécessairement celles de l''Union européenne ou de l''Agence exécutive européenne pour la santé et le numérique (HADEA). Ni l''Union européenne ni l''autorité subventionnaire ne peuvent en être tenues pour responsables.'),
  ('FOOTER', 'TERMS_TEXT', 'fr', 'En envoyant des messages à eduCGI, vous acceptez nos'),
  ('FOOTER', 'AND_READ', 'fr', 'et avez lu notre'),
  ('FOOTER', 'AND', 'fr', 'et'),
  ('SUGGESTIONS', 'CANCER_MUTATIONS', 'fr', 'Parlez-moi des mutations cancéreuses'),
  ('SUGGESTIONS', 'TREATMENT_OPTIONS', 'fr', 'Quelles sont les options de traitement ?'),
  ('SUGGESTIONS', 'GENOMIC_SEQUENCING', 'fr', 'Expliquez le séquençage génomique'),
  ('SUGGESTIONS', 'IMMUNOTHERAPY_WORK', 'fr', 'Comment fonctionne l''immunothérapie ?'),
  ('SUGGESTIONS', 'WHAT_IS_CANCER', 'fr', 'Qu''est-ce que le cancer ?'),
  ('SUGGESTIONS', 'CANCER_MUTATION', 'fr', 'Qu''est-ce qu''une mutation cancéreuse ?'),
  ('SUGGESTIONS', 'GENOMIC_SEQUENCING_DIAGNOSIS', 'fr', 'Comment le séquençage génomique aide-t-il au diagnostic du cancer ?'),
  ('SUGGESTIONS', 'SOMATIC_GERMLINE_DIFFERENCE', 'fr', 'Expliquez la différence entre les mutations somatiques et germinales.'),
  ('SOURCES', 'TITLE', 'fr', 'Source'),
  ('SOURCES', 'REFERENCES', 'fr', 'Références'),
  ('FEEDBACK', 'ADDITIONAL_FEEDBACK', 'fr', 'Retour supplémentaire'),
  ('FEEDBACK', 'TELL_US_MORE', 'fr', 'Dites-nous en plus sur votre expérience...'),
  ('FEEDBACK', 'CANCEL', 'fr', 'Annuler'),
  ('FEEDBACK', 'SUBMIT', 'fr', 'Soumettre'),
  ('FEEDBACK', 'SENDING', 'fr', 'Envoi du retour'),
  ('FEEDBACK', 'LIKE_SENT', 'fr', 'J''aime envoyé'),
  ('FEEDBACK', 'LIKE_ACTION', 'fr', 'J''aime cette réponse'),
  ('FEEDBACK', 'DISLIKE_SENT', 'fr', 'Je n''aime pas envoyé'),
  ('FEEDBACK', 'DISLIKE_ACTION', 'fr', 'Je n''aime pas cette réponse'),
  ('FEEDBACK', 'REGENERATE_RESPONSE', 'fr', 'Régénérer la réponse'),
  ('FEEDBACK', 'STOP', 'fr', 'Arrêter'),
  ('SIDEBAR', 'NEW_CHAT', 'fr', 'Nouvelle conversation'),
  ('SIDEBAR', 'CHAT_HISTORY', 'fr', 'Historique des conversations'),
  ('SIDEBAR', 'SEARCH_PLACEHOLDER', 'fr', 'Rechercher...'),
  ('SIDEBAR', 'CLEAR_HISTORY', 'fr', 'Effacer l''historique'),
  ('SIDEBAR', 'HEALTH_PROFILE', 'fr', 'Mon profil de santé'),
  ('SIDEBAR', 'HEALTH_PROFILE_TOOLTIP', 'fr', 'Voir votre profil de santé'),
  ('SIDEBAR', 'KNOW_MORE', 'fr', 'En savoir plus'),
  ('SIDEBAR', 'ABOUT_US', 'fr', 'À propos de nous'),
  ('SIDEBAR', 'FAQS', 'fr', 'FAQ'),
  ('SIDEBAR', 'SOURCES', 'fr', 'Sources'),
  ('SIDEBAR', 'NO_RECENT_CONVERSATIONS', 'fr', 'Aucune conversation récente'),
  ('SIDEBAR', 'NO_MATCHING_QUESTIONS', 'fr', 'Aucune question correspondante trouvée pour'),
  ('SIDEBAR', 'YOUR_CONVERSATIONS', 'fr', 'Vos conversations...'),
  ('SIDEBAR', 'ALL_QUESTIONS_ANSWERED', 'fr', 'Toutes les questions suggérées ont été répondues'),
  ('SIDEBAR', 'DELETE_CONVERSATION_CONFIRM', 'fr', 'Êtes-vous sûr de vouloir supprimer cette conversation ?'),
  ('SIDEBAR', 'HEALTH_PROFILE_INFO', 'fr', 'Ces informations de contexte seront utilisées comme filtre dans eduCGI'),
  ('SIDEBAR', 'HEALTH_PROFILE_TOGGLE_TOOLTIP', 'fr', 'Inclure ou exclure le profil de santé dans le chat'),
  ('SIDEBAR', 'HEALTH_PARAM_TUMOR_TYPE', 'fr', 'Type de tumeur'),
  ('SIDEBAR', 'HEALTH_PARAM_TUMOR_ALTERATION', 'fr', 'Altération de la tumeur'),
  ('SIDEBAR', 'HEALTH_PARAM_TREATMENT', 'fr', 'Traitement'),
  ('WELCOME', 'HELLO', 'fr', 'Bonjour'),
  ('WELCOME', 'HELP_TODAY', 'fr', 'Comment puis-je vous aider aujourd''hui ?'),
  ('WELCOME', 'SUGGESTED_QUESTIONS', 'fr', 'Questions suggérées'),
  ('HOME', 'WELCOME_TITLE', 'fr', 'Bienvenue sur eduCGI !'),
  ('HOME', 'DESCRIPTION_1', 'fr', 'En tant que <strong>chatbot IA</strong>, je suis ici pour vous aider à comprendre le monde complexe du cancer au niveau moléculaire. Mon objectif est de rendre les informations scientifiques plus accessibles, en fournissant des explications claires basées sur des sources fiables.'),
  ('HOME', 'DESCRIPTION_2', 'fr', '<strong>Veuillez noter : je suis une IA, pas un professionnel de santé.</strong> Les informations que je partage sont à but éducatif uniquement et ne doivent jamais être utilisées pour l''autodiagnostic ou pour prendre des décisions médicales. Consultez toujours un professionnel de santé qualifié pour des conseils et traitements médicaux personnalisés.'),
  ('HOME', 'AGREEMENT_TEXT', 'fr', 'eduCGI est développé dans le cadre du projet CGI-Clinics'),
  ('HOME', 'AGREEMENT_LINK', 'fr', 'accord CGI-Clinics 101057509'),
  ('HOME', 'START_BUTTON', 'fr', 'COMMENCER'),
  ('HOME', 'AGREEMENT_TITLE', 'fr', 'Accord CGI-Clinics 101057509'),
  ('HOME', 'AGREEMENT_CONTENT', 'fr', 'Financé par l''Union européenne. Les opinions exprimées n''engagent que leur(s) auteur(s) et ne reflètent pas nécessairement celles de l''Union européenne ou de l''Agence exécutive européenne pour la santé et le numérique (HADEA). Ni l''Union européenne ni l''autorité subventionnaire ne peuvent en être tenues pour responsables.'),
  ('HOME', 'CLOSE_BUTTON', 'fr', 'Fermer'),
  ('LEGAL', 'TERMS_TITLE', 'fr', 'Termes et Conditions'),
  ('LEGAL', 'PRIVACY_TITLE', 'fr', 'Politique de Confidentialité'),
  ('LEGAL', 'COOKIES_TITLE', 'fr', 'Politique de Cookies'),
  ('LEGAL', 'LEGAL_NOTICE_TITLE', 'fr', 'Mention Légale'),
  ('LEGAL', 'DEFAULT_TITLE', 'fr', 'Information Légale'),
  ('LEGAL', 'UNDER_REVISION', 'fr', 'Texte en révision'),
  ('LEGAL', 'PLACEHOLDER_TEXT', 'fr', 'Ce contenu est en cours de révision et sera disponible prochainement.'),
  ('LEGAL', 'BACK_HOME', 'fr', 'Retour à l''accueil'),
  ('HEADER', 'LOGOUT', 'de', 'ABMELDEN'),
  ('FOOTER', 'TERMS', 'de', 'Nutzungsbedingungen'),
  ('FOOTER', 'PRIVACY', 'de', 'Datenschutz'),
  ('FOOTER', 'COOKIES', 'de', 'Cookie-Richtlinie'),
  ('FOOTER', 'LEGAL_NOTICE', 'de', 'Rechtliche Hinweise'),
  ('FOOTER', 'GRANT_NUMBER', 'de', 'CGI-Clinics GA No.101057509.'),
  ('FOOTER', 'CGI_CLINICS', 'de', 'CGI-Clinics'),
  ('FOOTER', 'CANCER_GENOME_INTERPRETER', 'de', 'Cancer Genome Interpreter'),
  ('FOOTER', 'COPYRIGHT', 'de', '© 2025 | Cancer Genome Interpreter Clinics | Alle Rechte vorbehalten'),
  ('FOOTER', 'GRANT_INFO_TITLE', 'de', 'Förderinformationen'),
  ('FOOTER', 'GRANT_INFO_TEXT', 'de', 'Finanziert von der Europäischen Union. Die geäußerten Ansichten und Meinungen sind jedoch ausschließlich die des/der Autor(en) und spiegeln nicht unbedingt die der Europäischen Union oder der Europäischen Exekutivagentur für Gesundheit und Digitales (HADEA) wider. Weder die Europäische Union noch die Bewilligungsbehörde können für diese haftbar gemacht werden.'),
  ('FOOTER', 'TERMS_TEXT', 'de', 'Durch das Senden von Nachrichten an eduCGI stimmen Sie unseren'),
  ('FOOTER', 'AND_READ', 'de', 'zu und haben unsere'),
  ('FOOTER', 'AND', 'de', 'und'),
  ('SUGGESTIONS', 'CANCER_MUTATIONS', 'de', 'Erzählen Sie mir mehr über Krebsmutationen'),
  ('SUGGESTIONS', 'TREATMENT_OPTIONS', 'de', 'Was sind die Behandlungsoptionen?'),
  ('SUGGESTIONS', 'GENOMIC_SEQUENCING', 'de', 'Erklären Sie genomische Sequenzierung'),
  ('SUGGESTIONS', 'IMMUNOTHERAPY_WORK', 'de', 'Wie funktioniert Immuntherapie?'),
  ('SUGGESTIONS', 'WHAT_IS_CANCER', 'de', 'Was ist Krebs?'),
  ('SUGGESTIONS', 'CANCER_MUTATION', 'de', 'Was ist eine Krebsmutation?'),
  ('SUGGESTIONS', 'GENOMIC_SEQUENCING_DIAGNOSIS', 'de', 'Wie hilft genomische Sequenzierung bei der Krebsdiagnose?'),
  ('SUGGESTIONS', 'SOMATIC_GERMLINE_DIFFERENCE', 'de', 'Erklären Sie den Unterschied zwischen somatischen und Keimbahnmutationen.'),
  ('SOURCES', 'TITLE', 'de', 'Quelle'),
  ('SOURCES', 'REFERENCES', 'de', 'Referenzen'),
  ('FEEDBACK', 'ADDITIONAL_FEEDBACK', 'de', 'Zusätzliches Feedback'),
  ('FEEDBACK', 'TELL_US_MORE', 'de', 'Erzählen Sie uns mehr über Ihre Erfahrung...'),
  ('FEEDBACK', 'CANCEL', 'de', 'Abbrechen'),
  ('FEEDBACK', 'SUBMIT', 'de', 'Absenden'),
  ('FEEDBACK', 'SENDING', 'de', 'Feedback wird gesendet'),
  ('FEEDBACK', 'LIKE_SENT', 'de', 'Gefällt mir gesendet'),
  ('FEEDBACK', 'LIKE_ACTION', 'de', 'Diese Antwort gefällt mir'),
  ('FEEDBACK', 'DISLIKE_SENT', 'de', 'Gefällt mir nicht gesendet'),
  ('FEEDBACK', 'DISLIKE_ACTION', 'de', 'Diese Antwort gefällt mir nicht'),
  ('FEEDBACK', 'REGENERATE_RESPONSE', 'de', 'Antwort neu generieren'),
  ('FEEDBACK', 'STOP', 'de', 'Stoppen'),
  ('SIDEBAR', 'NEW_CHAT', 'de', 'Neuer Chat'),
  ('SIDEBAR', 'CHAT_HISTORY', 'de', 'Chat-Verlauf'),
  ('SIDEBAR', 'SEARCH_PLACEHOLDER', 'de', 'Suchen...'),
  ('SIDEBAR', 'CLEAR_HISTORY', 'de', 'Verlauf löschen'),
  ('SIDEBAR', 'HEALTH_PROFILE', 'de', 'Mein Gesundheitsprofil'),
  ('SIDEBAR', 'HEALTH_PROFILE_TOOLTIP', 'de', 'Gesundheitsprofil anzeigen'),
  ('SIDEBAR', 'KNOW_MORE', 'de', 'Mehr erfahren'),
  ('SIDEBAR', 'ABOUT_US', 'de', 'Über uns'),
  ('SIDEBAR', 'FAQS', 'de', 'FAQs'),
  ('SIDEBAR', 'SOURCES', 'de', 'Quellen'),
  ('SIDEBAR', 'NO_RECENT_CONVERSATIONS', 'de', 'Keine aktuellen Gespräche'),
  ('SIDEBAR', 'NO_MATCHING_QUESTIONS', 'de', 'Keine passenden Fragen gefunden für'),
  ('SIDEBAR', 'YOUR_CONVERSATIONS', 'de', 'Ihre Gespräche...'),
  ('SIDEBAR', 'ALL_QUESTIONS_ANSWERED', 'de', 'Alle vorgeschlagenen Fragen wurden beantwortet'),
  ('SIDEBAR', 'DELETE_CONVERSATION_CONFIRM', 'de', 'Möchten Sie dieses Gespräch wirklich löschen?'),
  ('SIDEBAR', 'HEALTH_PROFILE_INFO', 'de', 'Diese Kontextinformationen werden als Filter in eduCGI verwendet'),
  ('SIDEBAR', 'HEALTH_PROFILE_TOGGLE_TOOLTIP', 'de', 'Einschluss des Gesundheitsprofils im Chat umschalten'),
  ('SIDEBAR', 'HEALTH_PARAM_TUMOR_TYPE', 'de', 'Tumortyp'),
  ('SIDEBAR', 'HEALTH_PARAM_TUMOR_ALTERATION', 'de', 'Tumorveränderung'),
  ('SIDEBAR', 'HEALTH_PARAM_TREATMENT', 'de', 'Behandlung'),
  ('WELCOME', 'HELLO', 'de', 'Hallo'),
  ('WELCOME', 'HELP_TODAY', 'de', 'Wie kann ich Ihnen heute helfen?'),
  ('WELCOME', 'SUGGESTED_QUESTIONS', 'de', 'Vorgeschlagene Fragen'),
  ('HOME', 'WELCOME_TITLE', 'de', 'Willkommen bei eduCGI!'),
  ('HOME', 'DESCRIPTION_1', 'de', 'Als <strong>KI-Chatbot</strong> bin ich hier, um Ihnen zu helfen, die komplexe Welt des Krebses auf molekularer Ebene zu verstehen. Mein Ziel ist es, wissenschaftliche Informationen zugänglicher zu machen und klare Erklärungen auf der Grundlage zuverlässiger Quellen zu liefern.'),
  ('HOME', 'DESCRIPTION_2', 'de', '<strong>Bitte beachten Sie: Ich bin eine KI, kein medizinischer Fachmann.</strong> Die von mir geteilten Informationen dienen nur Bildungszwecken und sollten niemals zur Selbstdiagnose oder für medizinische Entscheidungen verwendet werden. Konsultieren Sie immer einen qualifizierten Arzt für persönliche medizinische Beratung und Behandlung.'),
  ('HOME', 'AGREEMENT_TEXT', 'de', 'eduCGI wird innerhalb des Projekts CGI-Clinics entwickelt'),
  ('HOME', 'AGREEMENT_LINK', 'de', 'Vereinbarung CGI-Clinics 101057509'),
  ('HOME', 'START_BUTTON', 'de', 'STARTEN'),
  ('HOME', 'AGREEMENT_TITLE', 'de', 'Vereinbarung CGI-Clinics 101057509'),
  ('HOME', 'AGREEMENT_CONTENT', 'de', 'Finanziert von der Europäischen Union. Die geäußerten Ansichten und Meinungen sind jedoch ausschließlich die des/der Autor(en) und spiegeln nicht unbedingt die der Europäischen Union oder der Europäischen Exekutivagentur für Gesundheit und Digitales (HADEA) wider. Weder die Europäische Union noch die Bewilligungsbehörde können für diese haftbar gemacht werden.'),
  ('HOME', 'CLOSE_BUTTON', 'de', 'Schließen'),
  ('LEGAL', 'TERMS_TITLE', 'de', 'Allgemeine Geschäftsbedingungen'),
  ('LEGAL', 'PRIVACY_TITLE', 'de', 'Datenschutzrichtlinie'),
  ('LEGAL', 'COOKIES_TITLE', 'de', 'Cookie-Richtlinie'),
  ('LEGAL', 'LEGAL_NOTICE_TITLE', 'de', 'Rechtlicher Hinweis'),
  ('LEGAL', 'DEFAULT_TITLE', 'de', 'Rechtliche Informationen'),
  ('LEGAL', 'UNDER_REVISION', 'de', 'Text in Überprüfung'),
  ('LEGAL', 'PLACEHOLDER_TEXT', 'de', 'Dieser Inhalt wird derzeit überprüft und wird in Kürze verfügbar sein.'),
  ('LEGAL', 'BACK_HOME', 'de', 'Zurück zur Startseite'),
  ('HEADER', 'LOGOUT', 'ca', 'TANCA DE SESSIÓ'),
  ('FOOTER', 'TERMS', 'ca', 'Termes'),
  ('FOOTER', 'PRIVACY', 'ca', 'Privadesa'),
  ('FOOTER', 'COOKIES', 'ca', 'Política de Cookies'),
  ('FOOTER', 'LEGAL_NOTICE', 'ca', 'Avís Legal'),
  ('FOOTER', 'GRANT_NUMBER', 'ca', 'CGI-Clinics GA No.101057509.'),
  ('FOOTER', 'CGI_CLINICS', 'ca', 'CGI-Clinics'),
  ('FOOTER', 'CANCER_GENOME_INTERPRETER', 'ca', 'Cancer Genome Interpreter'),
  ('FOOTER', 'COPYRIGHT', 'ca', '© 2025 | Cancer Genome Interpreter Clinics | Tots els drets reservats'),
  ('FOOTER', 'GRANT_INFO_TITLE', 'ca', 'Informació de la Subvenció'),
  ('FOOTER', 'GRANT_INFO_TEXT', 'ca', 'Finançat per la Unió Europea. Les opinions i punts de vista expressats són, però, els de l''autor o autors només i no reflecteixen necessàriament els de la Unió Europea o l''Agència Executiva de Salut i Digital (HADEA). Ni la Unió Europea ni l''autoritat concedent poden ser considerades responsables d''ells.'),
  ('FOOTER', 'TERMS_TEXT', 'ca', 'En enviar missatges a eduCGI, acceptes els nostres'),
  ('FOOTER', 'AND_READ', 'ca', 'i has llegit la nostra'),
  ('FOOTER', 'AND', 'ca', 'i'),
  ('SUGGESTIONS', 'CANCER_MUTATIONS', 'ca', 'Explica''m més sobre les mutacions cancerígenes'),
  ('SUGGESTIONS', 'TREATMENT_OPTIONS', 'ca', 'Quines són les opcions de tractament?'),
  ('SUGGESTIONS', 'GENOMIC_SEQUENCING', 'ca', 'Explica el seqüenciament genòmic'),
  ('SUGGESTIONS', 'IMMUNOTHERAPY_WORK', 'ca', 'Com funciona la immunoteràpia?'),
  ('SUGGESTIONS', 'WHAT_IS_CANCER', 'ca', 'Què és el càncer?'),
  ('SUGGESTIONS', 'CANCER_MUTATION', 'ca', 'Què és una mutació cancerígena?'),
  ('SUGGESTIONS', 'GENOMIC_SEQUENCING_DIAGNOSIS', 'ca', 'Com ajuda el seqüenciament genòmic en el diagnòstic del càncer?'),
  ('SUGGESTIONS', 'SOMATIC_GERMLINE_DIFFERENCE', 'ca', 'Explica la diferència entre mutacions somàtiques i germinals.'),
  ('SOURCES', 'TITLE', 'ca', 'Font'),
  ('SOURCES', 'REFERENCES', 'ca', 'Referències'),
  ('FEEDBACK', 'ADDITIONAL_FEEDBACK', 'ca', 'Comentaris addicionals'),
  ('FEEDBACK', 'TELL_US_MORE', 'ca', 'Explica''ns més sobre la teva experiència...'),
  ('FEEDBACK', 'CANCEL', 'ca', 'Cancel·lar'),
  ('FEEDBACK', 'SUBMIT', 'ca', 'Enviar'),
  ('FEEDBACK', 'SENDING', 'ca', 'Enviant comentaris'),
  ('FEEDBACK', 'LIKE_SENT', 'ca', 'M''agrada enviat'),
  ('FEEDBACK', 'LIKE_ACTION', 'ca', 'M''agrada aquesta resposta'),
  ('FEEDBACK', 'DISLIKE_SENT', 'ca', 'No m''agrada enviat'),
  ('FEEDBACK', 'DISLIKE_ACTION', 'ca', 'No m''agrada aquesta resposta'),
  ('FEEDBACK', 'REGENERATE_RESPONSE', 'ca', 'Regenerar resposta'),
  ('FEEDBACK', 'STOP', 'ca', 'Aturar'),
  ('SIDEBAR', 'NEW_CHAT', 'ca', 'Nova xerrada'),
  ('SIDEBAR', 'CHAT_HISTORY', 'ca', 'Historial de xerrades'),
  ('SIDEBAR', 'SEARCH_PLACEHOLDER', 'ca', 'Cercar...'),
  ('SIDEBAR', 'CLEAR_HISTORY', 'ca', 'Esborrar historial'),
  ('SIDEBAR', 'HEALTH_PROFILE', 'ca', 'El meu perfil de salut'),
  ('SIDEBAR', 'HEALTH_PROFILE_TOOLTIP', 'ca', 'Veure el teu perfil de salut'),
  ('SIDEBAR', 'KNOW_MORE', 'ca', 'Saber més'),
  ('SIDEBAR', 'ABOUT_US', 'ca', 'Sobre nosaltres'),
  ('SIDEBAR', 'FAQS', 'ca', 'PMF'),
  ('SIDEBAR', 'SOURCES', 'ca', 'Fonts'),
  ('SIDEBAR', 'NO_RECENT_CONVERSATIONS', 'ca', 'Cap conversa recent'),
  ('SIDEBAR', 'NO_MATCHING_QUESTIONS', 'ca', 'No s''han trobat preguntes coincidents amb'),
  ('SIDEBAR', 'YOUR_CONVERSATIONS', 'ca', 'Les teves converses...'),
  ('SIDEBAR', 'ALL_QUESTIONS_ANSWERED', 'ca', 'Totes les preguntes suggerides han estat respostes'),
  ('SIDEBAR', 'DELETE_CONVERSATION_CONFIRM', 'ca', 'Estàs segur que vols eliminar aquesta conversa?'),
  ('SIDEBAR', 'HEALTH_PROFILE_INFO', 'ca', 'Aquesta informació de context s''utilitzarà com a filtre a eduCGI'),
  ('SIDEBAR', 'HEALTH_PROFILE_TOGGLE_TOOLTIP', 'ca', 'Incloure o excloure el perfil de salut al xat'),
  ('SIDEBAR', 'HEALTH_PARAM_TUMOR_TYPE', 'ca', 'Tipus de tumor'),
  ('SIDEBAR', 'HEALTH_PARAM_TUMOR_ALTERATION', 'ca', 'Alteració del tumor'),
  ('SIDEBAR', 'HEALTH_PARAM_TREATMENT', 'ca', 'Tractament'),
  ('WELCOME', 'HELLO', 'ca', 'Hola'),
  ('WELCOME', 'HELP_TODAY', 'ca', 'Com puc ajudar-te avui?'),
  ('WELCOME', 'SUGGESTED_QUESTIONS', 'ca', 'Preguntes suggerides'),
  ('HOME', 'WELCOME_TITLE', 'ca', 'Benvingut/da a eduCGI!'),
  ('HOME', 'DESCRIPTION_1', 'ca', 'Com a <strong>chatbot d''IA</strong>, estic aquí per ajudar-te a entendre el món complex del càncer a nivell molecular. El meu objectiu és fer la informació científica més accessible, proporcionant explicacions clares basades en fonts fiables.'),
  ('HOME', 'DESCRIPTION_2', 'ca', '<strong>Recorda: sóc una IA, no un professional mèdic.</strong> La informació que comparteixo és només amb finalitats educatives i mai s''ha d''utilitzar per a autodiagnòstic o per prendre decisions mèdiques. Consulteu sempre amb un proveïdor de salut qualificat per a assessorament mèdic i tractament personalitzat.'),
  ('HOME', 'AGREEMENT_TEXT', 'ca', 'eduCGI es desenvolupa dins del projecte CGI-Clinics'),
  ('HOME', 'AGREEMENT_LINK', 'ca', 'acord CGI-Clinics 101057509'),
  ('HOME', 'START_BUTTON', 'ca', 'COMENÇAR'),
  ('HOME', 'AGREEMENT_TITLE', 'ca', 'Acord CGI-Clinics 101057509'),
  ('HOME', 'AGREEMENT_CONTENT', 'ca', 'Finançat per la Unió Europea. No obstant això, les opinions i punts de vista expressats són només dels autors i no reflecteixen necessàriament els de la Unió Europea o l''Agència Executiva Europea de Salut i Digital (HADEA). Ni la Unió Europea ni l''autoritat concessionària en són responsables.'),
  ('HOME', 'CLOSE_BUTTON', 'ca', 'Tancar'),
  ('LEGAL', 'TERMS_TITLE', 'ca', 'Termes i Condicions'),
  ('LEGAL', 'PRIVACY_TITLE', 'ca', 'Política de Privadesa'),
  ('LEGAL', 'COOKIES_TITLE', 'ca', 'Política de Cookies'),
  ('LEGAL', 'LEGAL_NOTICE_TITLE', 'ca', 'Avís Legal'),
  ('LEGAL', 'DEFAULT_TITLE', 'ca', 'Informació Legal'),
  ('LEGAL', 'UNDER_REVISION', 'ca', 'Text en revisió'),
  ('LEGAL', 'PLACEHOLDER_TEXT', 'ca', 'Aquest contingut està sent revisat i estarà disponible pròximament.'),
  ('LEGAL', 'BACK_HOME', 'ca', 'Tornar a l''inici'),
  ('HEADER', 'LOGOUT', 'el', 'ΑΠΟΣΥΝΔΕΣΗ'),
  ('FOOTER', 'TERMS', 'el', 'Όροι'),
  ('FOOTER', 'PRIVACY', 'el', 'Απόρρητο'),
  ('FOOTER', 'COOKIES', 'el', 'Πολιτική Cookies'),
  ('FOOTER', 'LEGAL_NOTICE', 'el', 'Νομική Ειδοποίηση'),
  ('FOOTER', 'GRANT_NUMBER', 'el', 'CGI-Clinics GA No.101057509.'),
  ('FOOTER', 'CGI_CLINICS', 'el', 'CGI-Clinics'),
  ('FOOTER', 'CANCER_GENOME_INTERPRETER', 'el', 'Cancer Genome Interpreter'),
  ('FOOTER', 'COPYRIGHT', 'el', '© 2025 | Cancer Genome Interpreter Clinics | Με επιφύλαξη παντός δικαιώματος'),
  ('FOOTER', 'GRANT_INFO_TITLE', 'el', 'Πληροφορίες Χρηματοδότησης'),
  ('FOOTER', 'GRANT_INFO_TEXT', 'el', 'Χρηματοδοτείται από την Ευρωπαϊκή Ένωση. Οι απόψεις και οι γνώμες που εκφράζονται είναι ωστόσο μόνο των συγγραφέων και δεν αντανακλούν απαραίτητα τις απόψεις της Ευρωπαϊκής Ένωσης ή του Ευρωπαϊκού Εκτελεστικού Οργανισμού Υγείας και Ψηφιοποίησης (HADEA). Ούτε η Ευρωπαϊκή Ένωση ούτε η χορηγούσα αρχή μπορούν να θεωρηθούν υπεύθυνες για αυτές.'),
  ('FOOTER', 'TERMS_TEXT', 'el', 'Με την αποστολή μηνυμάτων στο eduCGI, συμφωνείτε με τους'),
  ('FOOTER', 'AND_READ', 'el', 'και έχετε διαβάσει την'),
  ('FOOTER', 'AND', 'el', 'και'),
  ('SUGGESTIONS', 'CANCER_MUTATIONS', 'el', 'Πείτε μου περισσότερα για τις μεταλλάξεις καρκίνου'),
  ('SUGGESTIONS', 'TREATMENT_OPTIONS', 'el', 'Ποιες είναι οι επιλογές θεραπείας;'),
  ('SUGGESTIONS', 'GENOMIC_SEQUENCING', 'el', 'Εξηγήστε τη γονιδιακή αλληλούχιση'),
  ('SUGGESTIONS', 'IMMUNOTHERAPY_WORK', 'el', 'Πώς λειτουργεί η ανοσοθεραπεία;'),
  ('SUGGESTIONS', 'WHAT_IS_CANCER', 'el', 'Τι είναι ο καρκίνος;'),
  ('SUGGESTIONS', 'CANCER_MUTATION', 'el', 'Τι είναι μια μετάλλαξη καρκίνου;'),
  ('SUGGESTIONS', 'GENOMIC_SEQUENCING_DIAGNOSIS', 'el', 'Πώς βοηθά η γονιδιακή αλληλούχιση στη διάγνωση του καρκίνου;'),
  ('SUGGESTIONS', 'SOMATIC_GERMLINE_DIFFERENCE', 'el', 'Εξηγήστε τη διαφορά μεταξύ σωματικών και φυλετικών μεταλλάξεων.'),
  ('SOURCES', 'TITLE', 'el', 'Πηγή'),
  ('SOURCES', 'REFERENCES', 'el', 'Αναφορές'),
  ('FEEDBACK', 'ADDITIONAL_FEEDBACK', 'el', 'Πρόσθετη ανατροφοδότηση'),
  ('FEEDBACK', 'TELL_US_MORE', 'el', 'Πείτε μας περισσότερα για την εμπειρία σας...'),
  ('FEEDBACK', 'CANCEL', 'el', 'Ακύρωση'),
  ('FEEDBACK', 'SUBMIT', 'el', 'Υποβολή'),
  ('FEEDBACK', 'SENDING', 'el', 'Αποστολή ανατροφοδότησης'),
  ('FEEDBACK', 'LIKE_SENT', 'el', 'Μου αρέσει στάλθηκε'),
  ('FEEDBACK', 'LIKE_ACTION', 'el', 'Μου αρέσει αυτή η απάντηση'),
  ('FEEDBACK', 'DISLIKE_SENT', 'el', 'Δεν μου αρέσει στάλθηκε'),
  ('FEEDBACK', 'DISLIKE_ACTION', 'el', 'Δεν μου αρέσει αυτή η απάντηση'),
  ('FEEDBACK', 'REGENERATE_RESPONSE', 'el', 'Επαναδημιουργία απάντησης'),
  ('FEEDBACK', 'STOP', 'el', 'Διακοπή'),
  ('SIDEBAR', 'NEW_CHAT', 'el', 'Νέα συνομιλία'),
  ('SIDEBAR', 'CHAT_HISTORY', 'el', 'Ιστορικό συνομιλιών'),
  ('SIDEBAR', 'SEARCH_PLACEHOLDER', 'el', 'Αναζήτηση...'),
  ('SIDEBAR', 'CLEAR_HISTORY', 'el', 'Εκκαθάριση ιστορικού'),
  ('SIDEBAR', 'HEALTH_PROFILE', 'el', 'Το προφίλ υγείας μου'),
  ('SIDEBAR', 'HEALTH_PROFILE_TOOLTIP', 'el', 'Δείτε το προφίλ υγείας σας'),
  ('SIDEBAR', 'KNOW_MORE', 'el', 'Μάθετε περισσότερα'),
  ('SIDEBAR', 'ABOUT_US', 'el', 'Σχετικά με εμάς'),
  ('SIDEBAR', 'FAQS', 'el', 'Συχνές ερωτήσεις'),
  ('SIDEBAR', 'SOURCES', 'el', 'Πηγές'),
  ('SIDEBAR', 'NO_RECENT_CONVERSATIONS', 'el', 'Δεν υπάρχουν πρόσφατες συνομιλίες'),
  ('SIDEBAR', 'NO_MATCHING_QUESTIONS', 'el', 'Δεν βρέθηκαν ερωτήσεις που να ταιριάζουν με'),
  ('SIDEBAR', 'YOUR_CONVERSATIONS', 'el', 'Οι συνομιλίες σας...'),
  ('SIDEBAR', 'ALL_QUESTIONS_ANSWERED', 'el', 'Όλες οι προτεινόμενες ερωτήσεις έχουν απαντηθεί'),
  ('SIDEBAR', 'DELETE_CONVERSATION_CONFIRM', 'el', 'Είστε βέβαιοι ότι θέλετε να διαγράψετε αυτήν τη συνομιλία;'),
  ('SIDEBAR', 'HEALTH_PROFILE_INFO', 'el', 'Αυτές οι πληροφορίες περιεχομένου θα χρησιμοποιηθούν ως φίλτρο στο eduCGI'),
  ('SIDEBAR', 'HEALTH_PROFILE_TOGGLE_TOOLTIP', 'el', 'Εναλλαγή εισαγωγής του προφίλ υγείας στο chat'),
  ('SIDEBAR', 'HEALTH_PARAM_TUMOR_TYPE', 'el', 'Τύπος όγκου'),
  ('SIDEBAR', 'HEALTH_PARAM_TUMOR_ALTERATION', 'el', 'Μεταβολή όγκου'),
  ('SIDEBAR', 'HEALTH_PARAM_TREATMENT', 'el', 'Θεραπεία'),
  ('WELCOME', 'HELLO', 'el', 'Γεια σας'),
  ('WELCOME', 'HELP_TODAY', 'el', 'Πώς μπορώ να σας βοηθήσω σήμερα;'),
  ('WELCOME', 'SUGGESTED_QUESTIONS', 'el', 'Προτεινόμενες ερωτήσεις'),
  ('HOME', 'WELCOME_TITLE', 'el', 'Καλώς ήρθατε στο eduCGI!'),
  ('HOME', 'DESCRIPTION_1', 'el', 'Ως <strong>chatbot ΤΝ</strong>, είμαι εδώ για να σας βοηθήσω να κατανοήσετε τον σύνθετο κόσμο του καρκίνου σε μοριακό επίπεδο. Στόχος μου είναι να καταστήσω την επιστημονική πληροφόρηση πιο προσιτή, παρέχοντας σαφείς εξηγήσεις βασισμένες σε αξιόπιστες πηγές.'),
  ('HOME', 'DESCRIPTION_2', 'el', '<strong>Παρακαλώ σημειώστε: Είμαι ΤΝ, όχι ιατρικός επαγγελματίας.</strong> Οι πληροφορίες που μοιράζομαι είναι μόνο για εκπαιδευτικούς σκοπούς και δεν πρέπει ποτέ να χρησιμοποιηθούν για αυτοδιάγνωση ή για λήψη ιατρικών αποφάσεων. Συμβουλευτείτε πάντα έναν προσόντα επαγγελματία υγείας για εξατομικευμένες ιατρικές συμβουλές και θεραπεία.'),
  ('HOME', 'AGREEMENT_TEXT', 'el', 'Το eduCGI αναπτύσσεται στο πλαίσιο του έργου CGI-Clinics'),
  ('HOME', 'AGREEMENT_LINK', 'el', 'συμφωνία CGI-Clinics 101057509'),
  ('HOME', 'START_BUTTON', 'el', 'ΕΚΚΙΝΗΣΗ'),
  ('HOME', 'AGREEMENT_TITLE', 'el', 'Συμφωνία CGI-Clinics 101057509'),
  ('HOME', 'AGREEMENT_CONTENT', 'el', 'Χρηματοδοτείται από την Ευρωπαϊκή Ένωση. Οι απόψεις και οι γνώμες που εκφράζονται είναι ωστόσο μόνο των συγγραφέων και δεν αντανακλούν απαραίτητα τις απόψεις της Ευρωπαϊκής Ένωσης ή του Ευρωπαϊκού Εκτελεστικού Οργανισμού Υγείας και Ψηφιοποίησης (HADEA). Ούτε η Ευρωπαϊκή Ένωση ούτε η χορηγούσα αρχή μπορούν να θεωρηθούν υπεύθυνες για αυτές.'),
  ('HOME', 'CLOSE_BUTTON', 'el', 'Κλείσιμο'),
  ('LEGAL', 'TERMS_TITLE', 'el', 'Όροι και Προϋποθέσεις'),
  ('LEGAL', 'PRIVACY_TITLE', 'el', 'Πολιτική Απορρήτου'),
  ('LEGAL', 'COOKIES_TITLE', 'el', 'Πολιτική Cookies'),
  ('LEGAL', 'LEGAL_NOTICE_TITLE', 'el', 'Νομική Ειδοποίηση'),
  ('LEGAL', 'DEFAULT_TITLE', 'el', 'Νομικές Πληροφορίες'),
  ('LEGAL', 'UNDER_REVISION', 'el', 'Κείμενο υπό αναθεώρηση'),
  ('LEGAL', 'PLACEHOLDER_TEXT', 'el', 'Αυτό το περιεχόμενο βρίσκεται υπό αναθεώρηση και θα είναι διαθέσιμο σύντομα.'),
  ('LEGAL', 'BACK_HOME', 'el', 'Επιστροφή στην Αρχική')
on conflict (namespace, key, locale) do update set
  value = excluded.value,
  updated_at = now();
